swagger: "2.0"
info:
  title: Authentiq API
  version: "4"
  contact:
    name: Authentiq team
    url: "http://authentiq.io/support"
    email: "hello@authentiq.com"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  termsOfService: "http://authentiq.com/terms/"
host: 4-dot-authentiqio.appspot.com
basePath: /
schemes:
  - https
paths:
  /key:
    post:
      description: "Register a new ID `JWT(sub, devtoken)`"
      parameters:
        - $ref: "#/parameters/AuthentiqID"
      consumes:
        - application/jwt
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
        default:
          $ref: "#/responses/ErrorResponse"
    delete:
      description: "Revoke an Authentiq ID using email & phone.\n\nIf called with `email` and `phone` only, a verification code \nwill be sent by email. Do a second call adding `code` to \ncomplete the revocation.\n"
      parameters:
        - name: email
          in: query
          type: string
          description: primary email associated to Key (ID)
          required: true
        - name: phone
          in: query
          type: string
          description: "primary phone number, international representation"
          required: true
        - name: code
          in: query
          type: string
          description: verification code sent by email
          required: false
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              status:
                type: string
                description: pending or done
        "409":
          $ref: "#/responses/ErrorResponse"
        default:
          $ref: "#/responses/ErrorResponse"
  "/key/{PK}":
    get:
      description: "Gets `Key` object details.\n"
      parameters:
        - $ref: "#/parameters/PK"
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
          schema:
            title: JWT
            type: object
            properties:
              sub:
                type: string
                description: base64safe encoded public signing key
              status:
                type: string
              since:
                type: string
                format: date-time
        "410":
          $ref: "#/responses/ErrorResponse"
        default:
          $ref: "#/responses/ErrorResponse"
    post:
      description: "update properties of an Authentiq ID.\n(not operational in v4; use PUT for now)\n"
      parameters:
        - $ref: "#/parameters/PK"
        - $ref: "#/parameters/AuthentiqID"
      consumes:
        - application/jwt
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
        default:
          $ref: "#/responses/ErrorResponse"
    head:
      description: "HEAD info on Authentiq ID\n"
      parameters:
        - $ref: "#/parameters/PK"
      responses:
        "200":
          description: Successful response
        "410":
          $ref: "#/responses/ErrorResponse"
        default:
          $ref: "#/responses/ErrorResponse"
    put:
      description: "Update Authentiq ID by replacing the object.\n(v4: to bind email/phone hash)\n"
      parameters:
        - $ref: "#/parameters/PK"
        - $ref: "#/parameters/AuthentiqID"
      consumes:
        - application/jwt
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
        "409":
          $ref: "#/responses/ErrorResponse"
        default:
          $ref: "#/responses/ErrorResponse"
    delete:
      description: Revoke an Identity (Key) with a revocation secret
      parameters:
        - $ref: "#/parameters/PK"
        - name: secret
          in: query
          type: string
          description: revokation secret
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              status:
                type: string
                description: done
        "401":
          $ref: "#/responses/ErrorResponse"
        default:
          $ref: "#/responses/ErrorResponse"
definitions:
  AuthentiqID:
    description: "Authentiq ID in JWT format, self-signed"
    required:
      - sub
    properties:
      sub:
        description: UUID and public signing key
        type: string
      devtoken:
        description: device token for push messages
        type: string
      pk:
        description: public encryption key
        type: string
  Error:
    required:
      - error
    properties:
      error:
        type: integer
      type:
        type: string
        description: unique uri for this error
      title:
        type: string
      detail:
        type: string
parameters:
  PK:
    name: PK
    in: path
    description: Public Signing Key - Authentiq ID
    required: true
    type: string
  AuthentiqID:
    name: body
    in: body
    description: Authentiq ID to register
    required: true
    schema:
      $ref: "#/definitions/AuthentiqID"
responses:
  ErrorResponse:
    description: Error response
    schema:
      $ref: "#/definitions/Error"
