site_name: Authentiq Connect
site_url: http://developers.authentiq.io/
site_description: Documentation for the Authentiq OAuth 2.0 and OpenID Connect Provider.
site_author: The Authentiq team
site_favicon: images/app-icon-hexagon.png
# include_search: false
# use_absolute_urls: true
use_directory_urls: true
copyright: "©2015 authentiq.com"
# google_analytics: ['UA-X-Y', 'authentiq.io']
theme_dir: 'theme'
extra_css:
  - "//fonts.googleapis.com/css?family=Ubuntu|Ubuntu+Mono|Anonymous+Pro|PT+Mono|Roboto+Mono|Droid+Sans+Mono|Inconsolata|Fira+Mono|Source+Code+Pro"
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.smarty
pages:
  - 'Overview' : 'index.md'
  - 'Integration' : 'integration.md'
  - 'Installation' : 'installation.md'
  - 'API Reference' :
    - 'Connect' : 'api-provider.md'
    - 'Issuer' : 'api-issuer.md'
  - 'Your clients' : 'clients.md'
  - 'FAQ' : 'faq.md'
extra:
    version: 0.1.0  # {{ config.extra.version }}
    enable_tota11y: true
