site_name: Authentiq Connect
site_url: http://developers.authentiq.io/
site_description: Documentation for the Authentiq OAuth 2.0 and OpenID Connect Provider.
site_author: The Authentiq team
site_favicon: images/favicon.png
# include_search: false
# use_absolute_urls: true
use_directory_urls: true
copyright: '<span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Text" property="dct:title" rel="dct:type"><a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/AuthentiqID/authentiq-docs" rel="dct:source">Authentiq Connect Developer Documentation</a></span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.'
# google_analytics: ['UA-X-Y', 'authentiq.io']
theme_dir: 'theme'
extra_css:
  - "//fonts.googleapis.com/css?family=Ubuntu|Ubuntu+Mono|Anonymous+Pro|PT+Mono|Roboto+Mono|Droid+Sans+Mono|Inconsolata|Fira+Mono|Source+Code+Pro"
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.smarty
pages:
  - 'Overview': 'index.md'
  - 'Integration': 'integration.md'
  - 'Installation': 'installation.md'
  - 'API Reference':
    - 'Connect': 'api-provider.md'
    - 'Issuer': 'api-issuer.md'
  - 'Your Apps': 'yourapps.md'
  - 'FAQs': 'faq.md'
extra:
    version: 0.1.0  # {{ config.extra.version }}
    enable_tota11y: true
    snippet:
      client_id: test-js-snippet
      redirect_uri: /redirect.html
      scope: openid email~rs aq:name aq:push
extra_templates:
  - redirect.html
  - console.html
  - examples/signin.html
  - examples/events.html
