site_name: Authentiq Connect
site_url: http://developers.authentiq.com/
site_description: Documentation for the Authentiq OAuth 2.0 and OpenID Connect Provider.
site_author: The Authentiq team
repo_url: https://github.com/AuthentiqID/authentiq-docs/
edit_uri: edit/master/docs/
# include_search: false
# use_absolute_urls: true
use_directory_urls: true
copyright: '<span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Text" property="dct:title" rel="dct:type"><a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/AuthentiqID/authentiq-docs" rel="dct:source">Authentiq Connect Developer Documentation</a></span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.'
google_analytics: ['UA-74615018-3', 'developers.authentiq.com']
theme_dir: 'theme'
extra_css:
  #- "http://0.0.0.0:9001/dist/css/bootstrap-theme.css"
  - "//cdn.authentiq.io/theme/3.3.7aq1/css/bootstrap-theme.min.css"
  - "//fonts.googleapis.com/css?family=Montserrat:400,700|Noto+Serif:400|Material+Icons"
  - "css/base.css"
  #   - "//fonts.googleapis.com/css?family=Ubuntu|Ubuntu+Mono|Anonymous+Pro|PT+Mono|Roboto+Mono|Droid+Sans+Mono|Inconsolata|Fira+Mono|Source+Code+Pro"
markdown_extensions:
  - markdown.extensions.abbr
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.smarty
pages:
  - 'Overview': 'index.md'
#  - 'Get Started': 'gettingstarted.md'
  - 'Use Cases':
    - 'Signing in without a password': 'use-cases/passwordless-authentication.md'
    - 'Replacing two-step verification': 'use-cases/replace-two-step-verification.md'
  - 'API Reference': 'api-provider.md'
  - 'FAQ': 'faq.md'
extra:
    version: 0.1.0  # {{ config.extra.version }}
    enable_tota11y: true
    snippet:
      url: https://cdn.authentiq.io/authentiqjs/0.1.1-2/authentiq.js
      provider_uri: https://connect.authentiq.io/
      client_id: authentiq-connect-docs
      redirect_uri: /redirect.html
      scope: openid email~rs aq:name aq:push
extra_templates:
  - examples/signin.html
  - examples/events.html
