site_name: Authentiq Connect
site_description: Documentation for the Authentiq OAuth 2.0 and OpenID Connect Provider.
site_author: The Authentiq team
site_favicon: images/app-icon-hexagon.png
# site_url: http://authentiqid.github.io/authentiq-docs/
# include_search: false
# use_absolute_urls: true
use_directory_urls: true
copyright: Copyright &copy; 2015, Authentiq.com
# google_analytics: ['UA-6096819-11', 'docker.io']
theme_dir: 'docs_theme'
# theme: united
#extra_css:
#  - css/app.1512eea5d5df02a9286a.css
#  - css/bootstrap-theme.css
markdown_extensions:
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.smarty
pages:
  - 'Overview' : 'index.md'
  - 'Integration' : 'integration.md'
  - 'Installation' : 'installation.md'
  - 'API Reference' :
    - 'Connect' : 'api-provider.md'
    - 'Issuer' : 'api-issuer.md'
  - 'Your clients' : 'clients.md'
  - 'FAQ' : 'faq.md'
extra:
    version: 0.1.0  # {{ config.extra.version }}
