swagger: "2.0"
info:
  description: |
    Authentiq Client Management API.

    [Learn about Authentiq](http://authentiq.com) or join the IRC channel `#authentiq` on irc.freenode.net.

  version: "0.1.0"
  title: Authentiq Client Management
  termsOfService: http://authentiq.com/terms/
  contact:
    name: Authentiq team
    email: hello@authentiq.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: connect.authentiq.io
basePath: /v0
schemes:
  - https
paths:

  /client:
    get:
      summary: Get a list of Clients the current Account has access to
      description: ""
      operationId: getClientList
      produces:
        - application/json
      responses:
        default:
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Client"
      security:
        - aq_auth:
          - oidc

    post:
      summary: create a new Client in the current Account
      description: ""
      operationId: createClient
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Client object that needs to be added to the Account
          required: true
          schema:
            $ref: "#/definitions/Client"
      responses:
        "201":
          description: Success
          headers:
            "Location":
              description: "location of new Client object: /client/{clientId}"
              type: string
      security:
        - aq_auth:
          - oidc

  /client/{clientId}:
    get:
      summary: Get details of a Client object
      description: ""
      operationId: getClient
      produces:
        - application/json
      parameters:
        - in: path
          name: clientId
          description: "ID of client"
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Client"
        "401":
          description: No access to Client object
        "404":
          description: Client ID does not exist
      security:
        - aq_auth:
          - oidc

    put:
      summary: Update an existing client
      description: ""
      operationId: updateClient
      consumes:
        - application/json
      parameters:
        - in: path
          name: clientId
          description: "ID of client"
          required: true
          type: string
        - in: body
          name: body
          description: Client object that needs to be added to the Account
          required: true
          schema:
            $ref: "#/definitions/Client"
      responses:
        "401":
          description: No access to Client object
        "404":
          description: Client ID does not exist
        "200":
          description: Success
      security:
        - aq_auth:
          - oidc

    delete:
      summary: Delete a Client object
      description: ""
      operationId: deleteClient
      parameters:
        - in: path
          name: clientId
          description: "ID of client"
          required: true
          type: string
      responses:
        "200":
          description: Success
        "401":
          description: No access to Client object
        "404":
          description: Client ID does not exist
      security:
        - aq_auth:
          - oidc

securityDefinitions:
  aq_auth:
    type: oauth2
    authorizationUrl: https://connect.authentiq.io/authorize
    flow: implicit
    scopes:
      oidc: default iodc stuff
definitions:
  Client:
    properties:
      redirect_uris:
        type: array
        items:
          type: string
      response_types:
        type: array
        items:
          type: string
      grant_types:
        type: array
        items:
          type: string
      application_type:
        type: string
      application_type:
        type: string
      application_type:
        type: string
      contacts:
        type: array
        items:
          type: string
      client_name:
        type: string
      logo_uri:
        type: string
      client_uri:
        type: string
      policy_uri:
        type: string
      tos_uri:
        type: string
      default_max_age:
        type: integer
        format: int64
      default_scopes:
        type: array
        items:
          type: string

# END
